actions: improve package download reliability
I'd expect github to keep their images up to date with the latest
apt-get info, but apparently they don't.  On 2020-12-19, I reliably saw
actions failing with:
    E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/g/glibc/libc6-dbg_2.27-3ubuntu1.3_amd64.deb  404  Not Found [IP: 52.252.75.106 80]
    E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
    Error: Process completed with exit code 100.

However, when we add the `apt-get update`, the actions succeed with:
    Get:5 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main amd64 libc6-dbg amd64 2.27-3ubuntu1.4 [5163 kB]

(note that the version number is -3ubuntu1.4 instead of -3ubuntu1.3)