Actions: move from Ubuntu 18.04 to 20.04
1) (not actually part of the OS update)
   install autoconf-archive, so that autoconf can get the
   AX_CFLAGS_WARN_ALL directive.

2) clang-10 requires -Wno-implicit-fallthrough because it thinks that

       switch (foo) {
       case 0:
               bar();
               /* FALLTHROUGH */
       case 1:
               baz();
	       break;
       }

   looks like it has a missing 'break' in case 0.

3) silence gcc <sys/sysctrl.h> error:

    In file included from lib-platform/util/memlimit.c:43:
    /usr/include/x86_64-linux-gnu/sys/sysctl.h:21:2: error: #warning "The <sys/sysctl.h> header is deprecated and will be removed." [-Werror=cpp]
       21 | #warning "The <sys/sysctl.h> header is deprecated and will be removed."
          |  ^~~~~~~
    cc1: all warnings being treated as errors

   That's a really annoying warning because that code is protected by an

       #ifdef HAVE_SYS_SYSCTL_H

   In other words, autoconf already decided that the system provides
   <sys/sysctl.h> and it's ok to use it.

   memlimit.c happily uses other methods of querying the system, so
   there is absolutely nothing wrong with our code.